return function()
  local telescope = require("telescope")
  local config = require("plugins.telescope.config")
  telescope.load_extension("notify")
  telescope.load_extension("ui-select")
  telescope.load_extension("frecency")
  telescope.load_extension("smart_history")
  telescope.load_extension("fzy_native")
  telescope.setup(config)
end
