return {
  kind = {
    text = "",
    -- method = "m",
    -- function = "",
    -- constructor = "",
    method = "",
    ["function"] = "",
    constructor = "",
    field = "ﰠ", --"",
    variable = "",
    -- variable = "",
    class = "ﴯ", --"",
    interface = "",
    module = "",
    -- module = "",
    -- property = "",
    property = "ﰠ",
    unit = "",
    value = "",
    enum = "",
    keyword = "",
    -- keyword = "",
    snippet = "",
    -- snippet = "",
    color = "",
    file = "",
    reference = "",
    folder = "",
    enummember = "",
    -- constant = "",
    constant = "",
    -- struct = "פּ",
    struct = "",
    event = "",
    operator = "",
    typeparameter = "",
  },
  type = {
    array = "",
    number = "",
    string = "",
    boolean = "蘒",
    object = "",
  },
  documents = {
    arrow = {
      open = "",
      closed = "",
    },
    folder = {
      default = "",
      open = "",
      symlink = "",
      empty = "",
      empty_open = "",
    },
    file = {
      default = "",
      symlink = "",
      files = "",
    },
    git = {
      unstaged = "",
      staged = "s",
      unmerged = "",
      renamed = "➜",
      deleted = "",
      untracked = "u",
      ignored = "◌",
    },
  },
  git = {
    add = "",
    mod = "",
    remove = "",
    ignore = "",
    rename = "",
    diff = "",
    repo = "",
    branch = "",
  },
  ui = {
    lock = "",
    circle = "",
    bigcircle = "",
    bigunfilledcircle = "",
    close = "",
    newfile = "",
    search = "",
    lightbulb = "",
    project = "",
    dashboard = "",
    history = "",
    comment = "",
    bug = "",
    code = "",
    telescope = "",
    gear = "",
    package = "",
    list = "",
    signin = "",
    check = "",
    fire = "",
    tree = "",
    note = "",
    bookmark = "",
    pencil = "",
    -- chevronright = "",
    chevronright = ">",
    table = "",
    calendar = "",
    update = "",
  },
  diagnostics = {
    error = "", -- "", -- ""
    warning = "", -- "", -- ""
    information = "", -- "", -- ""
    question = "", --"", -- ""
    hint = "", -- "", -- ""
  },
  indicators = {
    errors = "", -- "", -- ""
    warnings = "", -- "", -- ""
    info = "", -- "", -- ""
    question = "", --"", -- ""
    hint = "", -- "", -- ""
    ok = "",
    spinnerframes = { "⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷" },
  },
  misc = {
    robot = "ﮧ",
    squirrel = "",
    tag = "",
    watch = "",
    terminal = ""
  },
}
