local t = require("tools")
local km = t.keymap
local mkm = t.modkeymap

km({ "n" }, "<esc>", ":noh<cr>", { desc = "Remove search highlights in normal mode" })
km({ "n", "x" }, "<space>", "<nop>", { desc = "Dont move cursor on space" })
--> top-level leader <--
km({ "n" }, "<leader>e", ":NvimTreeToggle<cr>", { desc = "Toggle NvimTree" })
km({ "n" }, "<leader>j", ":HopWord<cr>", { desc = "Hop!" })
--> splits <--
km({ "n" }, "<leader>-", ":new<cr>", { desc = "Horizonal split" })
km({ "n" }, "<leader>\\", ":vnew<cr>", { desc = "Vertical split" })
--> indentation <--
km({ "v" }, "<", "<gv", { desc = "Indent left" })
km({ "v" }, ">", ">gv", { desc = "Indent right" })
km({ "n" }, "<tab>", ">>_", { desc = "Indent left" })
km({ "n" }, "<s-tab>", "<<_", { desc = "Indent right" })
km({ "i" }, "<s-tab>", "<c-d>", { desc = "Indent right" })
km({ "v" }, "<tab>", ">gv", { desc = "Indent left" })
km({ "v" }, "<s-tab>", "<gv", { desc = "Indent right" })
--> move lines <--
km({ "n" }, "<a-j>", ":m .+1<cr>==", { desc = "Move line down" })
km({ "n" }, "<a-k>", ":m .-2<cr>==", { desc = "Move line up" })
km({ "v" }, "<a-j>", ":m '>+1<cr>gv=gv", { desc = "Move line down" })
km({ "v" }, "<a-k>", ":m '<-2<cr>gv=gv", { desc = "Move line up" })
km({ "x" }, "<a-j>", ":m '>+1<cr>gv-gv", { desc = "Move line down" })
km({ "x" }, "<a-k>", ":m '<-2<cr>gv-gv", { desc = "Move line up" })
--> move between windows <--
km({ "n" }, "<c-h>", ":SmartCursorMoveLeft<cr>", { desc = "Move to left window" })
km({ "n" }, "<c-j>", ":SmartCursorMoveDown<cr>", { desc = "Move to bottom window" })
km({ "n" }, "<c-k>", ":SmartCursorMoveUp<cr>", { desc = "Move to top window" })
km({ "n" }, "<c-l>", ":SmartCursorMoveRight<cr>", { desc = "Move to right window" })
--> resize windows <--
km({ "n" }, "<s-h>", ":SmartCursorMoveLeft<cr>", { desc = "Resize Left" })
km({ "n" }, "<s-j>", ":SmartCursorMoveDown<cr>", { desc = "Resize Down" })
km({ "n" }, "<s-k>", ":SmartCursorMoveUp<cr>", { desc = "Resize Up" })
km({ "n" }, "<s-l>", ":SmartCursorMoveRight<cr>", { desc = "Resize Right" })
--> move between tabs <--
km({ "n" }, "<a-h>", ":tabprevious<cr>", { desc = "Move to left tab" })
km({ "n" }, "<a-l>", ":tabnext<cr>", { desc = "Move to right tab" })
--> terminal mode <--
km({ "n" }, "<esc>", "<C-\\><C-N>", { desc = "Escape Terminal" })
km({ "t" }, "<esc>", "<C-\\><C-N><C-w>h", { desc = "Move to left window" })
km({ "t" }, "<esc>", "<C-\\><C-N><C-w>j", { desc = "Move to bottom window" })
km({ "t" }, "<esc>", "<C-\\><C-N><C-w>k", { desc = "Move to top window" })
km({ "t" }, "<esc>", "<C-\\><C-N><C-w>l", { desc = "Move to right window" })
--> command mode <--
mkm("telescope", { "c" }, "<c-r><c-r>", "<Plug>(TelescopeFuzzyCommandSearch)",
  { noremap = false, nowait = true, desc = "search command history" })
km({ "c" }, "<c-j>", 'pumvisible() ? "\\<C-n>" : "\\<C-j>"', { expr = true, noremap = true, desc = "Move to next item" })
km({ "c" }, "<c-k>", 'pumvisible() ? "\\<C-p>" : "\\<C-k>"',
  { expr = true, noremap = true, desc = "Move to previous item" })
--> Dep (Package Manager) <--
mkm("packer", { "n" }, "<leader>p", "Packer", { desc = "Package Manager" })
mkm("packer", { "n" }, "<leader>ps", ":PackerSync<cr>", { desc = "Sync" })
mkm("packer", { "n" }, "<leader>pS", ":PackerStatus<cr>", { desc = "Status" })
mkm("packer", { "n" }, "<leader>pu", ":PackerUpdate<cr>", { desc = "Update" })
mkm("packer", { "n" }, "<leader>pc", ":PackerClean<cr>", { desc = "Clean" })
mkm("packer", { "n" }, "<leader>pC", ":PackerCompile<cr>", { desc = "Compile" })
--> buffers <--
km({ "n" }, "<leader>b", "Buffer", { desc = "Buffer" })
mkm("neo-tree", { "n" }, "<leader>bs", ":Neotree buffers<cr>", { desc = "Show open buffers" })
--> lsp <--
-- mkm("lsp-setup", { "n" }, "gh", ":Lspsaga lsp_finder<cr>", { desc = "LSP Finder" })
mkm("lsp-setup", { "n" }, "gD", ":lua vim.lsp.buf.declaration()<cr>", { desc = "LSP Declaration" })
mkm("lsp-setup", { "n" }, "gd", ":lua vim.lsp.buf.definition()<cr>", { desc = "LSP Definition" })
mkm("lsp-setup", { "n" }, "gt", ":lua vim.lsp.buf.type_definition()<cr>", { desc = "LSP Type Definition" })
mkm("lsp-setup", { "n" }, "gi", ":lua vim.lsp.buf.implementation()<cr>", { desc = "LSP Implementation" })
mkm("lsp-setup", { "n" }, "gR", ":lua vim.lsp.buf.references()<cr>", { desc = "LSP References" })
mkm("lsp-setup", { "n" }, "K", ":lua vim.lsp.buf.hover()<cr>", { desc = "LSP Hover" })
mkm("lsp-setup", { "n" }, "<C-k>", ":lua vim.lsp.buf.signature_help()<cr>", { desc = "LSP Signature Help" })
mkm("lsp-setup", { "n" }, "[d", ":lua vim.diagnostic.goto_prev()<cr>", { desc = "LSP Goto Previous" })
mkm("lsp-setup", { "n" }, "]d", ":lua vim.diagnostic.goto_next()<cr>", { desc = "LSP Goto Next" })
-- mkm("lsp-setup", { "n" }, "gp", ":Lspsaga peek_definition<cr>", { desc = "Peek", silent = true })
--> lsp leader <--
mkm("lsp-setup", { "n" }, "<leader>l", "LSP", { desc = "LSP" })
mkm("lsp-setup", { "n" }, "<leader>ll", "Servers", { desc = "Servers" })
mkm("lsp-setup", { "n" }, "<leader>lll", ":LspLog<cr>", { desc = "Log" })
mkm("lsp-setup", { "n" }, "<leader>lli", ":LspInfo<cr>", { desc = "Info" })
mkm("lsp-setup", { "n" }, "<leader>llR", ":LspRestart<cr>", { desc = "Restart" })
mkm("copilot", { "n" }, "<leader>lC", ":CopilotPanel<cr>", { desc = "Copilot Panel" })
mkm("telescope", { "n" }, "<leader>ls", ":Telescope lsp_document_symbols<cr>", { desc = "Find" })
mkm("telescope", { "n" }, "<leader>lS", ":Telescope lsp_workspace_symbols<cr>", { desc = "Find" })
mkm("telescope", { "n" }, "<leader>lr", ":Telescope lsp_references<cr>", { desc = "References" })
mkm("telescope", { "n" }, "<leader>ld", ":Telescope lsp_definitions<cr>", { desc = "Definitions" })
mkm("telescope", { "n" }, "<leader>li", ":Telescope lsp_implementations<cr>", { desc = "Implementations" })
-- mkm("lsp-setup", { "n" }, "<leader>lc", ":Lspsaga code_action<cr>", { desc = "Code Action" })
-- mkm("lsp-setup", { "n" }, "<leader>lR", ":Lspsaga rename<cr>", { desc = "Rename" })
mkm("lsp-setup", { "n" }, "<leader>lf", ":lua vim.lsp.buf.format()<cr>", { desc = "Format" })
-- mkm("lsp-setup", { "n" }, "<leader>lp", ":Lspsaga peek_definition<cr>", { desc = "Peek", silent = true })
mkm("lsp-setup", { "n" }, "<leader>lm", "Mason", { desc = "Mason" })
mkm("lsp-setup", { "n" }, "<leader>lmm", ":Mason<cr>", { desc = "Open" })
mkm("lsp-setup", { "n" }, "<leader>lml", ":MasonLog<cr>", { desc = "Log" })
--> git <--
km({ "n" }, "<leader>g", "Git", { desc = "Git" })
mkm("neogit", { "n" }, "<leader>gg", ":Neogit<cr>", { desc = "Neogit" })
mkm("gitsigns", { "n" }, "<leader>gn", ":Neotree git_status<CR>", { desc = "Neotree git status" })
mkm("gitsigns", { "n" }, "<leader>gj", ":lua require 'gitsigns'.next_hunk()<CR>", { desc = "Next Hunk" })
mkm("gitsigns", { "n" }, "<leader>gk", ":lua require 'gitsigns'.prev_hunk()<CR>", { desc = "Prev Hunk" })
mkm("gitsigns", { "n" }, "<leader>gl", ":lua require 'gitsigns'.blame_line()<CR>", { desc = "Blame" })
mkm("gitsigns", { "n" }, "<leader>gp", ":lua require 'gitsigns'.preview_hunk()<CR>", { desc = "Preview Hunk" })
mkm("gitsigns", { "n" }, "<leader>gr", ":lua require 'gitsigns'.reset_hunk()<CR>", { desc = "Reset Hunk" })
mkm("gitsigns", { "n" }, "<leader>gR", ":lua require 'gitsigns'.reset_buffer()<CR>", { desc = "Reset Buffer" })
mkm("gitsigns", { "n" }, "<leader>gs", ":lua require 'gitsigns'.stage_hunk()<CR>", { desc = "Stage Hunk" })
mkm("gitsigns", { "n" }, "<leader>gu", ":lua require 'gitsigns'.undo_stage_hunk()<CR>", { desc = "Undo Stage Hunk" })
mkm("telescope", { "n" }, "<leader>go", ":Telescope git_status<CR>", { desc = "Open changed file" })
mkm("telescope", { "n" }, "<leader>gb", ":Telescope git_branches<CR>", { desc = "Checkout branch" })
mkm("telescope", { "n" }, "<leader>gc", ":Telescope git_commits<CR>", { desc = "Checkout commit" })
mkm("telescope", { "n" }, "<leader>gC", ":Telescope git_bcommits<CR>", { desc = "Checkout commit(for current file)" })
mkm("gitsigns", { "n" }, "<leader>gd", ":Gitsigns diffthis HEAD<CR>", { desc = "Git Diff" })
--> telescope <--
mkm("telescope", { "n" }, "<leader>t", "Telescope", { desc = "Telescope" })
mkm("telescope", { "n" }, "<leader>t?", ":Telescope<cr>", { desc = "Telescope builtins" })
mkm("telescope", { "n" }, "<leader>tF", ":Telescope frecency<cr>", { desc = "Frecency" })
mkm("telescope", { "n" }, "<leader>tB", ":Telescope buffers<cr>", { desc = "Buffers" })
mkm("telescope", { "n" }, "<leader>tN", ":Telescope notify<cr>", { desc = "Notify" })
mkm("telescope", { "n" }, "<leader>tb", ":Telescope git_branches<CR>", { desc = "Checkout branch" })
mkm("telescope", { "n" }, "<leader>tc", ":Telescope colorscheme<CR>", { desc = "Colorscheme" })
mkm("telescope", { "n" }, "<leader>tf", ":Telescope find_files<CR>", { desc = "Find File" })
mkm("telescope", { "n" }, "<leader>th", ":Telescope help_tags<CR>", { desc = "Find Help" })
mkm("telescope", { "n" }, "<leader>tM", ":Telescope man_pages<cr>", { desc = "Man Pages" })
mkm("telescope", { "n" }, "<leader>tm", ":Telescope oldfiles<cr>", { desc = "Old files" })
mkm("telescope", { "n" }, "<leader>tr", ":Telescope registers<cr>", { desc = "Registers" })
mkm("telescope", { "n" }, "<leader>tt", ":Telescope live_grep<cr>", { desc = "Text" })
mkm("telescope", { "n" }, "<leader>tk", ":Telescope keymaps<cr>", { desc = "Keymaps" })
mkm("telescope", { "n" }, "<leader>tC", ":Telescope commands<cr>", { desc = "Commands" })
