-- autogenerated lush spec on Thu 28 Apr 2022 10:20:44 PM CEST
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
return lush(function()
  return {
    SpecialKey                             { gui="bold", fg="#a9a1e1", }, -- SpecialKey     xxx ctermfg=81 gui=bold guifg=#a9a1e1
    EndOfBuffer                            { fg="#282c34", bg="#282c34", }, -- EndOfBuffer    xxx guifg=#282c34 guibg=#282c34
    TermCursor                             { gui="reverse", fg="#bbc2cf", }, -- TermCursor     xxx cterm=reverse gui=reverse guifg=#bbc2cf
    TermCursorNC                           { gui="reverse", fg="#5b6268", }, -- TermCursorNC   xxx gui=reverse guifg=#5B6268
    NonText                                { gui="bold", fg="#5b6268", }, -- NonText        xxx ctermfg=12 gui=bold guifg=#5B6268
    FidgetTask                             { NonText }, -- FidgetTask     xxx links to NonText
    Directory                              { gui="bold", fg="#a9a1e1", }, -- Directory      xxx ctermfg=159 gui=bold guifg=#a9a1e1
    TSNamespace                            { Directory }, -- TSNamespace    xxx links to Directory
    ErrorMsg                               { fg="white", bg="red", }, -- ErrorMsg       xxx ctermfg=15 ctermbg=1 guifg=White guibg=Red
    DiagnosticVirtualTextError             { ErrorMsg }, -- DiagnosticVirtualTextError xxx links to ErrorMsg
    DiagnosticFloatingError                { ErrorMsg }, -- DiagnosticFloatingError xxx links to ErrorMsg
    DiagnosticSignError                    { ErrorMsg }, -- DiagnosticSignError xxx links to ErrorMsg
    NvimInvalidSpacing                     { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    LspDiagnosticsFloatingError            { ErrorMsg }, -- LspDiagnosticsFloatingError xxx links to ErrorMsg
    LspDiagnosticsDefaultError             { ErrorMsg }, -- LspDiagnosticsDefaultError xxx links to ErrorMsg
    LspDiagnosticsVirtualTextError         { ErrorMsg }, -- LspDiagnosticsVirtualTextError xxx links to ErrorMsg
    LspDiagnosticsSignError                { ErrorMsg }, -- LspDiagnosticsSignError xxx links to ErrorMsg
    DiagnosticDefaultError                 { ErrorMsg }, -- DiagnosticDefaultError xxx links to ErrorMsg
    healthError                            { ErrorMsg }, -- healthError    xxx links to ErrorMsg
    TSDanger                               { ErrorMsg }, -- TSDanger       xxx links to ErrorMsg
    IncSearch                              { gui="bold", fg="#bbc2cf", bg="#2257a0", }, -- IncSearch      xxx cterm=reverse gui=bold guifg=#bbc2cf guibg=#2257A0
    MiniSurround                           { IncSearch }, -- MiniSurround   xxx links to IncSearch
    Search                                 { gui="bold", fg="#bbc2cf", bg="#2257a0", }, -- Search         xxx ctermfg=0 ctermbg=11 gui=bold guifg=#bbc2cf guibg=#2257A0
    QuickFixLine                           { Search }, -- QuickFixLine   xxx links to Search
    MiniTablineTabpagesection              { Search }, -- MiniTablineTabpagesection xxx links to Search
    MoreMsg                                { gui="bold", fg="seagreen", }, -- MoreMsg        xxx ctermfg=121 gui=bold guifg=SeaGreen
    DiagnosticVirtualTextInfo              { MoreMsg }, -- DiagnosticVirtualTextInfo xxx links to MoreMsg
    DiagnosticFloatingInfo                 { MoreMsg }, -- DiagnosticFloatingInfo xxx links to MoreMsg
    MiniStarterQuery                       { MoreMsg }, -- MiniStarterQuery xxx links to MoreMsg
    LspDiagnosticsFloatingInformation      { MoreMsg }, -- LspDiagnosticsFloatingInformation xxx links to MoreMsg
    LspDiagnosticsDefaultInformation       { MoreMsg }, -- LspDiagnosticsDefaultInformation xxx links to MoreMsg
    LspDiagnosticsVirtualTextInformation   { MoreMsg }, -- LspDiagnosticsVirtualTextInformation xxx links to MoreMsg
    LspDiagnosticsSignInformation          { MoreMsg }, -- LspDiagnosticsSignInformation xxx links to MoreMsg
    DiagnosticDefaultInfo                  { MoreMsg }, -- DiagnosticDefaultInfo xxx links to MoreMsg
    DiagnosticSignInformation              { MoreMsg }, -- DiagnosticSignInformation xxx links to MoreMsg
    ModeMsg                                { gui="bold", }, -- ModeMsg        xxx cterm=bold gui=bold
    LineNr                                 { fg="#3f444a", bg="#282c34", }, -- LineNr         xxx ctermfg=11 guifg=#3f444a guibg=#282c34
    LineNrAbove                            { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                            { LineNr }, -- LineNrBelow    xxx links to LineNr
    CursorLineNr                           { fg="#bbc2cf", bg="#21252a", }, -- CursorLineNr   xxx cterm=underline ctermfg=11 guifg=#bbc2cf guibg=#21252a
    Question                               { gui="bold", fg="#98be65", }, -- Question       xxx ctermfg=121 gui=bold guifg=#98be65
    StatusLine                             { fg="#dfdfdf", bg="#23272e", }, -- StatusLine     xxx cterm=bold,reverse guifg=#DFDFDF guibg=#23272e
    MsgSeparator                           { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    MiniTablineModifiedCurrent             { StatusLine }, -- MiniTablineModifiedCurrent xxx links to StatusLine
    MiniTablineModifiedVisible             { StatusLine }, -- MiniTablineModifiedVisible xxx links to StatusLine
    StatusLineNC                           { fg="#73797e", bg="#3e4556", }, -- StatusLineNC   xxx cterm=reverse guifg=#73797e guibg=#3E4556
    MiniTablineModifiedHidden              { StatusLineNC }, -- MiniTablineModifiedHidden xxx links to StatusLineNC
    VertSplit                              { fg="#3f444a", bg="#282c34", }, -- VertSplit      xxx cterm=reverse guifg=#3f444a guibg=#282c34
    WinSeparator                           { VertSplit }, -- WinSeparator   xxx links to VertSplit
    Title                                  { gui="bold", fg="#a9a1e1", }, -- Title          xxx ctermfg=225 gui=bold guifg=#a9a1e1
    MiniStarterFooter                      { Title }, -- MiniStarterFooter xxx links to Title
    MiniStarterHeader                      { Title }, -- MiniStarterHeader xxx links to Title
    FidgetTitle                            { Title }, -- FidgetTitle    xxx links to Title
    TSTitle                                { Title }, -- TSTitle        xxx links to Title
    Visual                                 { bg="#2257a0", }, -- Visual         xxx ctermbg=242 guibg=#2257A0
    WarningMsg                             { fg="red", }, -- WarningMsg     xxx ctermfg=224 guifg=Red
    DiagnosticVirtualTextWarn              { WarningMsg }, -- DiagnosticVirtualTextWarn xxx links to WarningMsg
    DiagnosticFloatingWarn                 { WarningMsg }, -- DiagnosticFloatingWarn xxx links to WarningMsg
    MiniStarterItemPrefix                  { WarningMsg }, -- MiniStarterItemPrefix xxx links to WarningMsg
    LspDiagnosticsFloatingWarning          { WarningMsg }, -- LspDiagnosticsFloatingWarning xxx links to WarningMsg
    LspDiagnosticsDefaultWarning           { WarningMsg }, -- LspDiagnosticsDefaultWarning xxx links to WarningMsg
    LspDiagnosticsVirtualTextWarning       { WarningMsg }, -- LspDiagnosticsVirtualTextWarning xxx links to WarningMsg
    LspDiagnosticsSignWarning              { WarningMsg }, -- LspDiagnosticsSignWarning xxx links to WarningMsg
    DiagnosticDefaultWarn                  { WarningMsg }, -- DiagnosticDefaultWarn xxx links to WarningMsg
    DiagnosticSignWarning                  { WarningMsg }, -- DiagnosticSignWarning xxx links to WarningMsg
    healthWarning                          { WarningMsg }, -- healthWarning  xxx links to WarningMsg
    TSWarning                              { WarningMsg }, -- TSWarning      xxx links to WarningMsg
    WildMenu                               { fg="#bbc2cf", bg="#2257a0", }, -- WildMenu       xxx ctermfg=0 ctermbg=11 guifg=#bbc2cf guibg=#2257A0
    Folded                                 { fg="#5b6268", bg="#21252a", }, -- Folded         xxx ctermfg=14 ctermbg=242 guifg=#5B6268 guibg=#21252a
    FoldColumn                             { fg="#5b6268", bg="#282c34", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=#5B6268 guibg=#282c34
    CursorLineFold                         { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    DiffAdd                                { bg="#42534f", }, -- DiffAdd        xxx guibg=#42534F
    DiffChange                             { bg="#42534f", }, -- DiffChange     xxx guibg=#42534F
    DiffDelete                             { bg="#7e7278", }, -- DiffDelete     xxx guibg=#7E7278
    DiffText                               { bg="#384643", }, -- DiffText       xxx guibg=#384643
    SignColumn                             { bg="#282c34", }, -- SignColumn     xxx ctermfg=14 ctermbg=242 guibg=#282c34
    CursorLineSign                         { SignColumn }, -- CursorLineSign xxx links to SignColumn
    Conceal                                { fg="#3f444a", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=#3f444a
    SpellBad                               { gui="undercurl", sp="red", }, -- SpellBad       xxx ctermbg=9 gui=undercurl guisp=Red
    SpellCap                               { gui="undercurl", sp="blue", }, -- SpellCap       xxx ctermbg=12 gui=undercurl guisp=Blue
    SpellRare                              { gui="undercurl", sp="magenta", }, -- SpellRare      xxx ctermbg=13 gui=undercurl guisp=Magenta
    SpellLocal                             { gui="undercurl", sp="cyan", }, -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=Cyan
    Pmenu                                  { fg="#bbc2cf", bg="#21252a", }, -- Pmenu          xxx ctermfg=0 ctermbg=13 guifg=#bbc2cf guibg=#21252a
    NormalFloat                            { Pmenu }, -- NormalFloat    xxx links to Pmenu
    PmenuSel                               { fg="#1b2229", bg="#51afef", }, -- PmenuSel       xxx ctermfg=242 ctermbg=0 guifg=#1B2229 guibg=#51afef
    PmenuSbar                              { bg="#21242b", }, -- PmenuSbar      xxx ctermbg=248 guibg=#21242b
    PmenuThumb                             { bg="#bbc2cf", }, -- PmenuThumb     xxx ctermbg=15 guibg=#bbc2cf
    TabLine                                { gui="bold", fg="#9ca0a4", bg="#21242b", }, -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 gui=bold guifg=#9ca0a4 guibg=#21242b
    MiniTablineHidden                      { TabLine }, -- MiniTablineHidden xxx links to TabLine
    TabLineSel                             { gui="bold", fg="#51afef", bg="#282c34", }, -- TabLineSel     xxx cterm=bold gui=bold guifg=#51afef guibg=#282c34
    MiniTablineCurrent                     { TabLineSel }, -- MiniTablineCurrent xxx links to TabLineSel
    MiniTablineVisible                     { TabLineSel }, -- MiniTablineVisible xxx links to TabLineSel
    TabLineFill                            { gui="bold", bg="#1c1f24", }, -- TabLineFill    xxx cterm=reverse gui=bold guibg=#1c1f24
    CursorColumn                           { bg="#21252a", }, -- CursorColumn   xxx ctermbg=242 guibg=#21252a
    CursorLine                             { bg="#21252a", }, -- CursorLine     xxx cterm=underline guibg=#21252a
    ColorColumn                            { bg="#21252a", }, -- ColorColumn    xxx ctermbg=1 guibg=#21252a
    Whitespace                             { fg="#3f444a", }, -- Whitespace     xxx guifg=#3f444a
    RedrawDebugNormal                      { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                       { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                    { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                   { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Cursor                                 { bg="#51afef", }, -- Cursor         xxx guibg=#51afef
    HopCursor                              { Cursor }, -- HopCursor      xxx links to Cursor
    lCursor                                { fg="bg", bg="fg", }, -- lCursor        xxx guifg=bg guibg=fg
    Normal                                 { fg="#bbc2cf", bg="#282c34", }, -- Normal         xxx guifg=#bbc2cf guibg=#282c34
    NvimSpacing                            { Normal }, -- NvimSpacing    xxx links to Normal
    NotifyERRORBody                        { Normal }, -- NotifyERRORBody xxx links to Normal
    NotifyWARNBody                         { Normal }, -- NotifyWARNBody xxx links to Normal
    NotifyINFOBody                         { Normal }, -- NotifyINFOBody xxx links to Normal
    NotifyDEBUGBody                        { Normal }, -- NotifyDEBUGBody xxx links to Normal
    NotifyTRACEBody                        { Normal }, -- NotifyTRACEBody xxx links to Normal
    MiniStarterItem                        { Normal }, -- MiniStarterItem xxx links to Normal
    Substitute                             { gui="bold,strikethrough", fg="#ff6c6b", }, -- Substitute     xxx gui=bold,strikethrough guifg=#ff6c6b
    FloatShadow                            { bg="black", blend="80", }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                     { bg="black", blend="100", }, -- FloatShadowThrough xxx guibg=Black blend=100
    Error                                  { fg="white", bg="red", }, -- Error          xxx ctermfg=15 ctermbg=9 guifg=White guibg=Red
    NvimInvalid                            { Error }, -- NvimInvalid    xxx links to Error
    TSError                                { Error }, -- TSError        xxx links to Error
    luaParenError                          { Error }, -- luaParenError  xxx links to Error
    luaBraceError                          { Error }, -- luaBraceError  xxx links to Error
    luaError                               { Error }, -- luaError       xxx links to Error
    Todo                                   { fg="blue", bg="yellow", }, -- Todo           xxx ctermfg=0 ctermbg=11 guifg=Blue guibg=Yellow
    luaTodo                                { Todo }, -- luaTodo        xxx links to Todo
    TSTodo                                 { Todo }, -- TSTodo         xxx links to Todo
    String                                 { fg="#98be65", }, -- String         xxx guifg=#98be65
    NvimString                             { String }, -- NvimString     xxx links to String
    TSString                               { String }, -- TSString       xxx links to String
    luaString2                             { String }, -- luaString2     xxx links to String
    luaString                              { String }, -- luaString      xxx links to String
    TSLiteral                              { String }, -- TSLiteral      xxx links to String
    Constant                               { gui="bold", fg="#a9a1e1", }, -- Constant       xxx ctermfg=13 gui=bold guifg=#a9a1e1
    TSConstant                             { Constant }, -- TSConstant     xxx links to Constant
    TSConstBuiltin                         { Constant }, -- TSConstBuiltin xxx links to Constant
    luaConstant                            { Constant }, -- luaConstant    xxx links to Constant
    AerialConstantIcon                     { Constant }, -- AerialConstantIcon xxx links to Constant
    TSTextReference                        { Constant }, -- TSTextReference xxx links to Constant
    Character                              { gui="bold", fg="#a9a1e1", }, -- Character      xxx gui=bold guifg=#a9a1e1
    TSCharacter                            { Character }, -- TSCharacter    xxx links to Character
    Number                                 { fg="#da8548", }, -- Number         xxx guifg=#da8548
    NvimNumber                             { Number }, -- NvimNumber     xxx links to Number
    TSNumber                               { Number }, -- TSNumber       xxx links to Number
    luaNumber                              { Number }, -- luaNumber      xxx links to Number
    Boolean                                { gui="bold", fg="#da8548", }, -- Boolean        xxx gui=bold guifg=#da8548
    TSBoolean                              { Boolean }, -- TSBoolean      xxx links to Boolean
    Float                                  { fg="#da8548", }, -- Float          xxx guifg=#da8548
    TSFloat                                { Float }, -- TSFloat        xxx links to Float
    Function                               { fg="#c678dd", }, -- Function       xxx guifg=#c678dd
    TSFunction                             { Function }, -- TSFunction     xxx links to Function
    luaFunction                            { Function }, -- luaFunction    xxx links to Function
    AerialFunctionIcon                     { Function }, -- AerialFunctionIcon xxx links to Function
    AerialMethodIcon                       { Function }, -- AerialMethodIcon xxx links to Function
    Identifier                             { fg="#ffa8ff", }, -- Identifier     xxx cterm=bold ctermfg=14 guifg=#FFA8FF
    NvimIdentifier                         { Identifier }, -- NvimIdentifier xxx links to Identifier
    luaFunc                                { Identifier }, -- luaFunc        xxx links to Identifier
    AerialArrayIcon                        { Identifier }, -- AerialArrayIcon xxx links to Identifier
    AerialBooleanIcon                      { Identifier }, -- AerialBooleanIcon xxx links to Identifier
    AerialEnumMemberIcon                   { Identifier }, -- AerialEnumMemberIcon xxx links to Identifier
    AerialEventIcon                        { Identifier }, -- AerialEventIcon xxx links to Identifier
    AerialFieldIcon                        { Identifier }, -- AerialFieldIcon xxx links to Identifier
    AerialFileIcon                         { Identifier }, -- AerialFileIcon xxx links to Identifier
    AerialKeyIcon                          { Identifier }, -- AerialKeyIcon  xxx links to Identifier
    AerialNullIcon                         { Identifier }, -- AerialNullIcon xxx links to Identifier
    AerialNumberIcon                       { Identifier }, -- AerialNumberIcon xxx links to Identifier
    AerialObjectIcon                       { Identifier }, -- AerialObjectIcon xxx links to Identifier
    AerialOperatorIcon                     { Identifier }, -- AerialOperatorIcon xxx links to Identifier
    AerialPropertyIcon                     { Identifier }, -- AerialPropertyIcon xxx links to Identifier
    AerialStringIcon                       { Identifier }, -- AerialStringIcon xxx links to Identifier
    AerialTypeParameterIcon                { Identifier }, -- AerialTypeParameterIcon xxx links to Identifier
    AerialVariableIcon                     { Identifier }, -- AerialVariableIcon xxx links to Identifier
    TSSymbol                               { Identifier }, -- TSSymbol       xxx links to Identifier
    Conditional                            { fg="#51afef", }, -- Conditional    xxx guifg=#51afef
    TSConditional                          { Conditional }, -- TSConditional  xxx links to Conditional
    luaElse                                { Conditional }, -- luaElse        xxx links to Conditional
    luaCond                                { Conditional }, -- luaCond        xxx links to Conditional
    Statement                              { fg="#51afef", }, -- Statement      xxx ctermfg=11 guifg=#51afef
    luaStatement                           { Statement }, -- luaStatement   xxx links to Statement
    Repeat                                 { fg="#51afef", }, -- Repeat         xxx guifg=#51afef
    TSRepeat                               { Repeat }, -- TSRepeat       xxx links to Repeat
    luaRepeat                              { Repeat }, -- luaRepeat      xxx links to Repeat
    luaFor                                 { Repeat }, -- luaFor         xxx links to Repeat
    Label                                  { fg="#51afef", }, -- Label          xxx guifg=#51afef
    TSLabel                                { Label }, -- TSLabel        xxx links to Label
    luaLabel                               { Label }, -- luaLabel       xxx links to Label
    Operator                               { fg="#51afef", }, -- Operator       xxx guifg=#51afef
    NvimAssignment                         { Operator }, -- NvimAssignment xxx links to Operator
    NvimOperator                           { Operator }, -- NvimOperator   xxx links to Operator
    TSOperator                             { Operator }, -- TSOperator     xxx links to Operator
    luaIn                                  { Operator }, -- luaIn          xxx links to Operator
    luaOperator                            { Operator }, -- luaOperator    xxx links to Operator
    Keyword                                { fg="#51afef", }, -- Keyword        xxx guifg=#51afef
    TSKeyword                              { Keyword }, -- TSKeyword      xxx links to Keyword
    Exception                              { fg="#51afef", }, -- Exception      xxx guifg=#51afef
    TSException                            { Exception }, -- TSException    xxx links to Exception
    Include                                { gui="bold", fg="#a9a1e1", }, -- Include        xxx gui=bold guifg=#a9a1e1
    TSInclude                              { Include }, -- TSInclude      xxx links to Include
    AerialModuleIcon                       { Include }, -- AerialModuleIcon xxx links to Include
    AerialNamespaceIcon                    { Include }, -- AerialNamespaceIcon xxx links to Include
    AerialPackageIcon                      { Include }, -- AerialPackageIcon xxx links to Include
    PreProc                                { gui="bold", fg="#a9a1e1", }, -- PreProc        xxx ctermfg=81 gui=bold guifg=#a9a1e1
    TSAnnotation                           { PreProc }, -- TSAnnotation   xxx links to PreProc
    TSPreProc                              { PreProc }, -- TSPreProc      xxx links to PreProc
    Define                                 { gui="bold", fg="#a9a1e1", }, -- Define         xxx gui=bold guifg=#a9a1e1
    TSDefine                               { Define }, -- TSDefine       xxx links to Define
    Macro                                  { fg="#a9a1e1", }, -- Macro          xxx guifg=#a9a1e1
    TSConstMacro                           { Macro }, -- TSConstMacro   xxx links to Macro
    TSFuncMacro                            { Macro }, -- TSFuncMacro    xxx links to Macro
    TSEnvironment                          { Macro }, -- TSEnvironment  xxx links to Macro
    PreCondit                              { gui="bold", fg="#a9a1e1", }, -- PreCondit      xxx gui=bold guifg=#a9a1e1
    StorageClass                           { fg="#51afef", }, -- StorageClass   xxx guifg=#51afef
    TSStorageClass                         { StorageClass }, -- TSStorageClass xxx links to StorageClass
    Type                                   { fg="#ecbe7b", }, -- Type           xxx ctermfg=121 guifg=#ECBE7B
    NvimNumberPrefix                       { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                        { Type }, -- NvimOptionSigil xxx links to Type
    TSType                                 { Type }, -- TSType         xxx links to Type
    AerialClassIcon                        { Type }, -- AerialClassIcon xxx links to Type
    AerialEnumIcon                         { Type }, -- AerialEnumIcon xxx links to Type
    AerialInterfaceIcon                    { Type }, -- AerialInterfaceIcon xxx links to Type
    AerialStructIcon                       { Type }, -- AerialStructIcon xxx links to Type
    TSTypeQualifier                        { Type }, -- TSTypeQualifier xxx links to Type
    TSEnvironmentName                      { Type }, -- TSEnvironmentName xxx links to Type
    Structure                              { fg="#51afef", }, -- Structure      xxx guifg=#51afef
    TSConstructor                          { Structure }, -- TSConstructor  xxx links to Structure
    luaTable                               { Structure }, -- luaTable       xxx links to Structure
    Typedef                                { fg="#51afef", }, -- Typedef        xxx guifg=#51afef
    TSTypeDefinition                       { Typedef }, -- TSTypeDefinition xxx links to Typedef
    Tag                                    { gui="bold", fg="#4bc4f7", }, -- Tag            xxx gui=bold guifg=#4BC4F7
    TSTag                                  { Tag }, -- TSTag          xxx links to Tag
    Special                                { fg="#a9a1e1", }, -- Special        xxx ctermfg=224 guifg=#a9a1e1
    Debug                                  { Special }, -- Debug          xxx links to Special
    NotifyLogTitle                         { Special }, -- NotifyLogTitle xxx links to Special
    AerialConstructorIcon                  { Special }, -- AerialConstructorIcon xxx links to Special
    TSMath                                 { Special }, -- TSMath         xxx links to Special
    SpecialChar                            { gui="bold", fg="#dfdfdf", }, -- SpecialChar    xxx gui=bold guifg=#DFDFDF
    NvimRegister                           { SpecialChar }, -- NvimRegister   xxx links to SpecialChar
    NvimStringSpecial                      { SpecialChar }, -- NvimStringSpecial xxx links to SpecialChar
    luaSpecial                             { SpecialChar }, -- luaSpecial     xxx links to SpecialChar
    TSStringSpecial                        { SpecialChar }, -- TSStringSpecial xxx links to SpecialChar
    TSCharacterSpecial                     { SpecialChar }, -- TSCharacterSpecial xxx links to SpecialChar
    Delimiter                              { fg="#51afef", }, -- Delimiter      xxx guifg=#51afef
    NvimParenthesis                        { Delimiter }, -- NvimParenthesis xxx links to Delimiter
    NvimColon                              { Delimiter }, -- NvimColon      xxx links to Delimiter
    NvimComma                              { Delimiter }, -- NvimComma      xxx links to Delimiter
    NvimArrow                              { Delimiter }, -- NvimArrow      xxx links to Delimiter
    MiniStarterItemBullet                  { Delimiter }, -- MiniStarterItemBullet xxx links to Delimiter
    MiniStarterSection                     { Delimiter }, -- MiniStarterSection xxx links to Delimiter
    MiniIndentscopeSymbol                  { Delimiter }, -- MiniIndentscopeSymbol xxx links to Delimiter
    TSPunctDelimiter                       { Delimiter }, -- TSPunctDelimiter xxx links to Delimiter
    TSPunctBracket                         { Delimiter }, -- TSPunctBracket xxx links to Delimiter
    TSPunctSpecial                         { Delimiter }, -- TSPunctSpecial xxx links to Delimiter
    TSTagDelimiter                         { Delimiter }, -- TSTagDelimiter xxx links to Delimiter
    SpecialComment                         { gui="bold", fg="#9ca0a4", }, -- SpecialComment xxx gui=bold guifg=#9ca0a4
    TSNote                                 { SpecialComment }, -- TSNote         xxx links to SpecialComment
    DiagnosticError                        { fg="red", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticWarn                         { fg="orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticSignWarn                     { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    DiagnosticInfo                         { fg="lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticSignInfo                     { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    DiagnosticHint                         { fg="lightgrey", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticUnderlineError               { gui="underline", sp="red", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineWarn                { gui="underline", sp="orange", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticUnderlineInfo                { gui="underline", sp="lightblue", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineHint                { gui="underline", sp="lightgrey", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    MatchParen                             { gui="bold", fg="#ff6c6b", }, -- MatchParen     xxx ctermbg=6 gui=bold guifg=#ff6c6b
    Comment                                { fg="#5b6268", }, -- Comment        xxx ctermfg=14 guifg=#5B6268
    NotifyLogTime                          { Comment }, -- NotifyLogTime  xxx links to Comment
    MiniStarterInactive                    { Comment }, -- MiniStarterInactive xxx links to Comment
    Noise                                  { Comment }, -- Noise          xxx links to Comment
    netrwTreeBar                           { Comment }, -- netrwTreeBar   xxx links to Comment
    TSComment                              { Comment }, -- TSComment      xxx links to Comment
    luaComment                             { Comment }, -- luaComment     xxx links to Comment
    AerialGuide                            { Comment }, -- AerialGuide    xxx links to Comment
    gitblame                               { Comment }, -- gitblame       xxx links to Comment
    Underlined                             { gui="underline", fg="#4bc4f7", }, -- Underlined     xxx cterm=underline ctermfg=81 gui=underline guifg=#4BC4F7
    Ignore                                 { fg="bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                      { fg="red", bg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                        { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape          { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape   { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    NotifyERRORBorder                      { fg="#8a1f1f", }, -- NotifyERRORBorder xxx guifg=#8A1F1F
    NotifyWARNBorder                       { fg="#79491d", }, -- NotifyWARNBorder xxx guifg=#79491D
    NotifyINFOBorder                       { fg="#4f6752", }, -- NotifyINFOBorder xxx guifg=#4F6752
    NotifyDEBUGBorder                      { fg="#8b8b8b", }, -- NotifyDEBUGBorder xxx guifg=#8B8B8B
    NotifyTRACEBorder                      { fg="#4f3552", }, -- NotifyTRACEBorder xxx guifg=#4F3552
    NotifyERRORIcon                        { fg="#f70067", }, -- NotifyERRORIcon xxx guifg=#F70067
    NotifyWARNIcon                         { fg="#f79000", }, -- NotifyWARNIcon xxx guifg=#F79000
    NotifyINFOIcon                         { fg="#a9ff68", }, -- NotifyINFOIcon xxx guifg=#A9FF68
    NotifyDEBUGIcon                        { fg="#8b8b8b", }, -- NotifyDEBUGIcon xxx guifg=#8B8B8B
    NotifyTRACEIcon                        { fg="#d484ff", }, -- NotifyTRACEIcon xxx guifg=#D484FF
    NotifyERRORTitle                       { fg="#f70067", }, -- NotifyERRORTitle xxx guifg=#F70067
    NotifyWARNTitle                        { fg="#f79000", }, -- NotifyWARNTitle xxx guifg=#F79000
    NotifyINFOTitle                        { fg="#a9ff68", }, -- NotifyINFOTitle xxx guifg=#A9FF68
    NotifyDEBUGTitle                       { fg="#8b8b8b", }, -- NotifyDEBUGTitle xxx guifg=#8B8B8B
    NotifyTRACETitle                       { fg="#d484ff", }, -- NotifyTRACETitle xxx guifg=#D484FF
    DevIconPy                              { fg="#3572a5", }, -- DevIconPy      xxx guifg=#3572A5
    DevIconPng                             { fg="#a074c4", }, -- DevIconPng     xxx guifg=#a074c4
    DevIconPl                              { fg="#519aba", }, -- DevIconPl      xxx guifg=#519aba
    DevIconMdx                             { fg="#519aba", }, -- DevIconMdx     xxx guifg=#519aba
    DevIconMd                              { fg="#519aba", }, -- DevIconMd      xxx guifg=#519aba
    DevIconPhp                             { fg="#a074c4", }, -- DevIconPhp     xxx guifg=#a074c4
    DevIconMakefile                        { fg="#6d8086", }, -- DevIconMakefile xxx guifg=#6d8086
    DevIconDockerfile                      { fg="#384d54", }, -- DevIconDockerfile xxx guifg=#384d54
    DevIconLicense                         { fg="#cbcb41", }, -- DevIconLicense xxx guifg=#cbcb41
    DevIconMarkdown                        { fg="#519aba", }, -- DevIconMarkdown xxx guifg=#519aba
    DevIconJpg                             { fg="#a074c4", }, -- DevIconJpg     xxx guifg=#a074c4
    DevIconJpeg                            { fg="#a074c4", }, -- DevIconJpeg    xxx guifg=#a074c4
    DevIconIco                             { fg="#cbcb41", }, -- DevIconIco     xxx guifg=#cbcb41
    DevIconJs                              { fg="#cbcb41", }, -- DevIconJs      xxx guifg=#cbcb41
    DevIconHtm                             { fg="#e34c26", }, -- DevIconHtm     xxx guifg=#e34c26
    DevIconJson                            { fg="#cbcb41", }, -- DevIconJson    xxx guifg=#cbcb41
    DevIconVim                             { fg="#019833", }, -- DevIconVim     xxx guifg=#019833
    DevIconDb                              { fg="#dad8d8", }, -- DevIconDb      xxx guifg=#dad8d8
    DevIconGo                              { fg="#519aba", }, -- DevIconGo      xxx guifg=#519aba
    DevIconDart                            { fg="#03589c", }, -- DevIconDart    xxx guifg=#03589C
    DevIconCpp                             { fg="#519aba", }, -- DevIconCpp     xxx guifg=#519aba
    DevIconLua                             { fg="#51a0cf", }, -- DevIconLua     xxx guifg=#51a0cf
    DevIconNodeModules                     { fg="#e8274b", }, -- DevIconNodeModules xxx guifg=#E8274B
    DevIconGemfile                         { fg="#701516", }, -- DevIconGemfile xxx guifg=#701516
    DevIconZshrc                           { fg="#89e051", }, -- DevIconZshrc   xxx guifg=#89e051
    DevIconBash                            { fg="#89e051", }, -- DevIconBash    xxx guifg=#89e051
    DevIconVimrc                           { fg="#019833", }, -- DevIconVimrc   xxx guifg=#019833
    DevIconSh                              { fg="#4d5a5e", }, -- DevIconSh      xxx guifg=#4d5a5e
    DevIconGvimrc                          { fg="#019833", }, -- DevIconGvimrc  xxx guifg=#019833
    DevIconGitIgnore                       { fg="#41535b", }, -- DevIconGitIgnore xxx guifg=#41535b
    DevIconGitConfig                       { fg="#41535b", }, -- DevIconGitConfig xxx guifg=#41535b
    DevIconGitAttributes                   { fg="#41535b", }, -- DevIconGitAttributes xxx guifg=#41535b
    DevIconSvg                             { fg="#ffb13b", }, -- DevIconSvg     xxx guifg=#FFB13B
    DevIconVue                             { fg="#8dc149", }, -- DevIconVue     xxx guifg=#8dc149
    DevIconCPlusPlus                       { fg="#f34b7d", }, -- DevIconCPlusPlus xxx guifg=#f34b7d
    DevIconCss                             { fg="#563d7c", }, -- DevIconCss     xxx guifg=#563d7c
    DevIconHtml                            { fg="#e34c26", }, -- DevIconHtml    xxx guifg=#e34c26
    DevIconConf                            { fg="#6d8086", }, -- DevIconConf    xxx guifg=#6d8086
    DevIconCp                              { fg="#519aba", }, -- DevIconCp      xxx guifg=#519aba
    DevIconWebp                            { fg="#a074c4", }, -- DevIconWebp    xxx guifg=#a074c4
    DevIconC                               { fg="#599eff", }, -- DevIconC       xxx guifg=#599eff
    DevIconYaml                            { fg="#6d8086", }, -- DevIconYaml    xxx guifg=#6d8086
    DevIconToml                            { fg="#6d8086", }, -- DevIconToml    xxx guifg=#6d8086
    DevIconSwift                           { fg="#e37933", }, -- DevIconSwift   xxx guifg=#e37933
    DevIconSql                             { fg="#dad8d8", }, -- DevIconSql     xxx guifg=#dad8d8
    DevIconTerminal                        { fg="#31b53e", }, -- DevIconTerminal xxx guifg=#31B53E
    DevIconZsh                             { fg="#89e051", }, -- DevIconZsh     xxx guifg=#89e051
    DevIconYml                             { fg="#6d8086", }, -- DevIconYml     xxx guifg=#6d8086
    DevIconJava                            { fg="#cc3e44", }, -- DevIconJava    xxx guifg=#cc3e44
    DevIconJsx                             { fg="#519aba", }, -- DevIconJsx     xxx guifg=#519aba
    DevIconRs                              { fg="#dea584", }, -- DevIconRs      xxx guifg=#dea584
    DevIconRb                              { fg="#701516", }, -- DevIconRb      xxx guifg=#701516
    DevIconNPMIgnore                       { fg="#e8274b", }, -- DevIconNPMIgnore xxx guifg=#E8274B
    DevIconScala                           { fg="#cc3e44", }, -- DevIconScala   xxx guifg=#cc3e44
    DevIconRss                             { fg="#fb9d3b", }, -- DevIconRss     xxx guifg=#FB9D3B
    DevIconGitLogo                         { fg="#f14c28", }, -- DevIconGitLogo xxx guifg=#F14C28
    DevIconRakefile                        { fg="#701516", }, -- DevIconRakefile xxx guifg=#701516
    DevIconTsx                             { fg="#519aba", }, -- DevIconTsx     xxx guifg=#519aba
    DevIconRake                            { fg="#701516", }, -- DevIconRake    xxx guifg=#701516
    DevIconPyo                             { fg="#519aba", }, -- DevIconPyo     xxx guifg=#519aba
    DevIconR                               { fg="#358a5b", }, -- DevIconR       xxx ctermfg=65 guifg=#358a5b
    DevIconPyd                             { fg="#519aba", }, -- DevIconPyd     xxx guifg=#519aba
    DevIconFish                            { fg="#4d5a5e", }, -- DevIconFish    xxx guifg=#4d5a5e
    DevIconPyc                             { fg="#519aba", }, -- DevIconPyc     xxx guifg=#519aba
    DevIconTs                              { fg="#519aba", }, -- DevIconTs      xxx guifg=#519aba
    DevIconDefault                         { fg="#6d8086", }, -- DevIconDefault xxx guifg=#6d8086
    WhichKey                               { fg="#51afef", }, -- WhichKey       xxx guifg=#51afef
    WhichKeyFloat                          { bg="#202328", }, -- WhichKeyFloat  xxx guibg=#202328
    WhichKeyDesc                           { fg="#c678dd", }, -- WhichKeyDesc   xxx guifg=#c678dd
    WhichKeyGroup                          { fg="#c678dd", }, -- WhichKeyGroup  xxx guifg=#c678dd
    WhichKeyValue                          { fg="#3f444a", }, -- WhichKeyValue  xxx guifg=#3f444a
    WhichKeySeparator                      { fg="#5b6268", }, -- WhichKeySeparator xxx guifg=#5B6268
    CmpItemAbbrDefault                     { fg="#bbc2cf", }, -- CmpItemAbbrDefault xxx guifg=#bbc2cf
    CmpItemAbbr                            { CmpItemAbbrDefault }, -- CmpItemAbbr    xxx links to CmpItemAbbrDefault
    CmpItemAbbrDeprecatedDefault           { fg="#5b6268", }, -- CmpItemAbbrDeprecatedDefault xxx guifg=#5b6268
    CmpItemAbbrDeprecated                  { CmpItemAbbrDeprecatedDefault }, -- CmpItemAbbrDeprecated xxx links to CmpItemAbbrDeprecatedDefault
    CmpItemAbbrMatchDefault                { fg="#bbc2cf", }, -- CmpItemAbbrMatchDefault xxx guifg=#bbc2cf
    CmpItemAbbrMatch                       { CmpItemAbbrMatchDefault }, -- CmpItemAbbrMatch xxx links to CmpItemAbbrMatchDefault
    CmpItemAbbrMatchFuzzyDefault           { fg="#bbc2cf", }, -- CmpItemAbbrMatchFuzzyDefault xxx guifg=#bbc2cf
    CmpItemAbbrMatchFuzzy                  { CmpItemAbbrMatchFuzzyDefault }, -- CmpItemAbbrMatchFuzzy xxx links to CmpItemAbbrMatchFuzzyDefault
    CmpItemKindDefault                     { fg="#a9a1e1", }, -- CmpItemKindDefault xxx guifg=#a9a1e1
    CmpItemKind                            { CmpItemKindDefault }, -- CmpItemKind    xxx links to CmpItemKindDefault
    CmpItemMenuDefault                     { fg="#bbc2cf", }, -- CmpItemMenuDefault xxx guifg=#bbc2cf
    CmpItemMenu                            { CmpItemMenuDefault }, -- CmpItemMenu    xxx links to CmpItemMenuDefault
    Separator                              { fg="#5b6268", }, -- Separator      xxx guifg=#5B6268
    PmenuSelBold                           { gui="bold", fg="#1b2229", bg="#51afef", }, -- PmenuSelBold   xxx gui=bold guifg=#1B2229 guibg=#51afef
    StatusLinePartNC                       { gui="bold", fg="#73797e", bg="#3e4556", }, -- StatusLinePartNC xxx gui=bold guifg=#73797e guibg=#3E4556
    StatusLinePart                         { gui="bold", fg="#73797e", bg="#3e4556", }, -- StatusLinePart xxx gui=bold guifg=#73797e guibg=#3E4556
    TermNormalNC                           { fg="#bbc2cf", bg="#282c34", }, -- TermNormalNC   xxx guifg=#bbc2cf guibg=#282c34
    TermNormal                             { fg="#bbc2cf", bg="#282c34", }, -- TermNormal     xxx guifg=#bbc2cf guibg=#282c34
    IndentGuideOdd                         { fg="#3f444a", }, -- IndentGuideOdd xxx guifg=#3f444a
    IndentGuideEven                        { fg="#3f444a", }, -- IndentGuideEven xxx guifg=#3f444a
    IndentGuide                            { fg="#3f444a", }, -- IndentGuide    xxx guifg=#3f444a
    NvimTreeIndentMarker                   { IndentGuide }, -- NvimTreeIndentMarker xxx links to IndentGuide
    VisualBold                             { gui="bold", bg="#2257a0", }, -- VisualBold     xxx gui=bold guibg=#2257A0
    NormalPopupSubtle                      { fg="#73797e", bg="#3e4556", }, -- NormalPopupSubtle xxx guifg=#73797e guibg=#3E4556
    NormalPopupPrompt                      { gui="bold", fg="#9ca0a4", bg="#2b303c", }, -- NormalPopupPrompt xxx gui=bold guifg=#9ca0a4 guibg=#2B303C
    NormalPopover                          { fg="#e0e8f8", bg="#3e4556", }, -- NormalPopover  xxx guifg=#E0E8F8 guibg=#3E4556
    NormalPopup                            { fg="#e0e8f8", bg="#3e4556", }, -- NormalPopup    xxx guifg=#E0E8F8 guibg=#3E4556
    Emphasis                               { gui="bold", fg="#98be65", }, -- Emphasis       xxx gui=bold guifg=#98be65
    Bold                                   { gui="bold", }, -- Bold           xxx gui=bold
    TSStrong                               { Bold }, -- TSStrong       xxx links to Bold
    File                                   { fg="#bbc2cf", }, -- File           xxx guifg=#bbc2cf
    HighlightSubtle                        { bg="#4a4a45", }, -- HighlightSubtle xxx guibg=#4A4A45
    Highlight                              { bg="#4a4a45", }, -- Highlight      xxx guibg=#4A4A45
    IncSearchCursor                        { gui="reverse", }, -- IncSearchCursor xxx gui=reverse
    LspHighlight                           { bg="#21252a", }, -- LspHighlight   xxx guibg=#21252a
    LspReferenceText                       { LspHighlight }, -- LspReferenceText xxx links to LspHighlight
    LspReferenceRead                       { LspHighlight }, -- LspReferenceRead xxx links to LspHighlight
    LspReferenceWrite                      { LspHighlight }, -- LspReferenceWrite xxx links to LspHighlight
    TextMuted                              { fg="#9ca0a4", }, -- TextMuted      xxx guifg=#9ca0a4
    DiagnosticVirtualTextHint              { TextMuted }, -- DiagnosticVirtualTextHint xxx links to TextMuted
    TextMutedBold                          { gui="bold", fg="#9ca0a4", }, -- TextMutedBold  xxx gui=bold guifg=#9ca0a4
    TextSuccess                            { fg="#98be65", }, -- TextSuccess    xxx guifg=#98be65
    Msg                                    { TextSuccess }, -- Msg            xxx links to TextSuccess
    TextSuccessBold                        { gui="bold", fg="#98be65", }, -- TextSuccessBold xxx gui=bold guifg=#98be65
    TextDebug                              { fg="#ecbe7b", }, -- TextDebug      xxx guifg=#ECBE7B
    TextDebugBold                          { gui="bold", fg="#ecbe7b", }, -- TextDebugBold  xxx gui=bold guifg=#ECBE7B
    TextError                              { fg="#ff6c6b", }, -- TextError      xxx guifg=#ff6c6b
    TextErrorBold                          { gui="bold", fg="#ff6c6b", }, -- TextErrorBold  xxx gui=bold guifg=#ff6c6b
    TextNormal                             { fg="#bbc2cf", }, -- TextNormal     xxx guifg=#bbc2cf
    TextNormalBold                         { gui="bold", fg="#bbc2cf", }, -- TextNormalBold xxx gui=bold guifg=#bbc2cf
    TextSpecial                            { fg="#a9a1e1", }, -- TextSpecial    xxx guifg=#a9a1e1
    TextSpecialBold                        { gui="bold", fg="#a9a1e1", }, -- TextSpecialBold xxx gui=bold guifg=#a9a1e1
    TextInfo                               { fg="#51afef", }, -- TextInfo       xxx guifg=#51afef
    TextInfoBold                           { gui="bold", fg="#51afef", }, -- TextInfoBold   xxx gui=bold guifg=#51afef
    TextWarning                            { fg="#ecbe7b", }, -- TextWarning    xxx guifg=#ECBE7B
    TextWarningBold                        { gui="bold", fg="#ecbe7b", }, -- TextWarningBold xxx gui=bold guifg=#ECBE7B
    RegexpKey                              { gui="bold", fg="#5f0041", }, -- RegexpKey      xxx gui=bold guifg=#5f0041
    Property                               { fg="#c678dd", }, -- Property       xxx guifg=#c678dd
    TSProperty                             { Property }, -- TSProperty     xxx links to Property
    RegexpDelimiter                        { gui="bold", fg="#540063", }, -- RegexpDelimiter xxx gui=bold guifg=#540063
    Attribute                              { fg="#ffa8ff", }, -- Attribute      xxx guifg=#FFA8FF
    TSAttribute                            { Attribute }, -- TSAttribute    xxx links to Attribute
    Regexp                                 { fg="#dd0093", }, -- Regexp         xxx guifg=#dd0093
    Class                                  { fg="#51afef", }, -- Class          xxx guifg=#51afef
    Variable                               { fg="#8b93e6", }, -- Variable       xxx guifg=#8B93E6
    SpecialBold                            { gui="bold", fg="#a9a1e1", }, -- SpecialBold    xxx gui=bold guifg=#a9a1e1
    Field                                  { fg="#a9a1e1", }, -- Field          xxx guifg=#a9a1e1
    TSField                                { Field }, -- TSField        xxx links to Field
    Method                                 { fg="#a9a1e1", }, -- Method         xxx guifg=#a9a1e1
    TSMethod                               { Method }, -- TSMethod       xxx links to Method
    KeywordFunction                        { fg="#51afef", }, -- KeywordFunction xxx guifg=#51afef
    TSKeywordFunction                      { KeywordFunction }, -- TSKeywordFunction xxx links to KeywordFunction
    RegexpSpecial                          { fg="#a40073", }, -- RegexpSpecial  xxx guifg=#a40073
    TypeBuiltin                            { gui="bold", fg="#ecbe7b", }, -- TypeBuiltin    xxx gui=bold guifg=#ECBE7B
    TSTypeBuiltin                          { TypeBuiltin }, -- TSTypeBuiltin  xxx links to TypeBuiltin
    FunctionBuiltin                        { gui="bold", fg="#ffa8ff", }, -- FunctionBuiltin xxx gui=bold guifg=#FFA8FF
    TSFuncBuiltin                          { FunctionBuiltin }, -- TSFuncBuiltin  xxx links to FunctionBuiltin
    Argument                               { fg="#ffa8ff", }, -- Argument       xxx guifg=#FFA8FF
    TSParameter                            { Argument }, -- TSParameter    xxx links to Argument
    TSParameterReference                   { Argument }, -- TSParameterReference xxx links to Argument
    StringDelimiter                        { fg="#98be65", }, -- StringDelimiter xxx guifg=#98be65
    TSStringRegex                          { StringDelimiter }, -- TSStringRegex  xxx links to StringDelimiter
    TSStringEscape                         { StringDelimiter }, -- TSStringEscape xxx links to StringDelimiter
    VariableBuiltin                        { gui="bold", fg="#8b93e6", }, -- VariableBuiltin xxx gui=bold guifg=#8B93E6
    TSVariableBuiltin                      { VariableBuiltin }, -- TSVariableBuiltin xxx links to VariableBuiltin
    Enum                                   { fg="#da8548", }, -- Enum           xxx guifg=#da8548
    CommentBold                            { gui="bold", fg="#5b6268", }, -- CommentBold    xxx gui=bold guifg=#5B6268
    CommentLabel                           { CommentBold }, -- CommentLabel   xxx links to CommentBold
    CommentSection                         { CommentBold }, -- CommentSection xxx links to CommentBold
    URL                                    { gui="underline", fg="#98be65", }, -- URL            xxx gui=underline guifg=#98be65
    CommentURL                             { URL }, -- CommentURL     xxx links to URL
    TSURI                                  { URL }, -- TSURI          xxx links to URL
    Link                                   { gui="underline", fg="#98be65", }, -- Link           xxx gui=underline guifg=#98be65
    DiffModified                           { fg="#bbc2cf", bg="#6e7984", }, -- DiffModified   xxx guifg=#bbc2cf guibg=#6E7984
    DiffAdded                              { fg="#a6bf8f", bg="#42534f", }, -- DiffAdded      xxx guifg=#A6BF8F guibg=#42534F
    diffLine                               { fg="#dfdfdf", bg="#4b525c", }, -- diffLine       xxx guifg=#DFDFDF guibg=#4B525C
    diffSubName                            { fg="#dfdfdf", bg="#4b525c", }, -- diffSubName    xxx guifg=#DFDFDF guibg=#4B525C
    DiffRemovedGutterLineNr                { fg="#3f444a", }, -- DiffRemovedGutterLineNr xxx guifg=#3f444a
    DiffModifiedGutterLineNr               { fg="#3f444a", }, -- DiffModifiedGutterLineNr xxx guifg=#3f444a
    DiffAddedGutterLineNr                  { fg="#3f444a", }, -- DiffAddedGutterLineNr xxx guifg=#3f444a
    DiffRemovedGutter                      { gui="bold", fg="#ff6c6b", }, -- DiffRemovedGutter xxx gui=bold guifg=#ff6c6b
    GitSignsDelete                         { DiffRemovedGutter }, -- GitSignsDelete xxx links to DiffRemovedGutter
    NvimTreeGitDeleted                     { DiffRemovedGutter }, -- NvimTreeGitDeleted xxx links to DiffRemovedGutter
    DiffModifiedGutter                     { gui="bold", fg="#da8548", }, -- DiffModifiedGutter xxx gui=bold guifg=#da8548
    GitSignsChange                         { DiffModifiedGutter }, -- GitSignsChange xxx links to DiffModifiedGutter
    GitSignsChangeDelete                   { DiffModifiedGutter }, -- GitSignsChangeDelete xxx links to DiffModifiedGutter
    NvimTreeGitDirty                       { DiffModifiedGutter }, -- NvimTreeGitDirty xxx links to DiffModifiedGutter
    NvimTreeGitStaged                      { DiffModifiedGutter }, -- NvimTreeGitStaged xxx links to DiffModifiedGutter
    NvimTreeGitMerge                       { DiffModifiedGutter }, -- NvimTreeGitMerge xxx links to DiffModifiedGutter
    NvimTreeGitRenamed                     { DiffModifiedGutter }, -- NvimTreeGitRenamed xxx links to DiffModifiedGutter
    DiffAddedGutter                        { gui="bold", fg="#98be65", }, -- DiffAddedGutter xxx gui=bold guifg=#98be65
    GitSignsAdd                            { DiffAddedGutter }, -- GitSignsAdd    xxx links to DiffAddedGutter
    NvimTreeGitNew                         { DiffAddedGutter }, -- NvimTreeGitNew xxx links to DiffAddedGutter
    DiffRemoved                            { fg="#d69fa7", bg="#534f56", }, -- DiffRemoved    xxx guifg=#D69FA7 guibg=#534F56
    markdownCode                           { bg="#21252a", }, -- markdownCode   xxx guibg=#21252a
    markdownLinkText                       { gui="underline", }, -- markdownLinkText xxx gui=underline
    markdownH2                             { gui="bold", }, -- markdownH2     xxx gui=bold
    markdownH1                             { gui="bold", }, -- markdownH1     xxx gui=bold
    markdownCodeBlock                      { bg="#21252a", }, -- markdownCodeBlock xxx guibg=#21252a
    netrwMakefile                          { fg="#ecbe7b", }, -- netrwMakefile  xxx guifg=#ECBE7B
    netrwExe                               { fg="#98be65", }, -- netrwExe       xxx guifg=#98be65
    netrwDir                               { fg="#51afef", }, -- netrwDir       xxx guifg=#51afef
    netrwClassify                          { fg="#51afef", }, -- netrwClassify  xxx guifg=#51afef
    BufferInactiveTarget                   { gui="bold", fg="#ff6c6b", bg="#1c1f24", }, -- BufferInactiveTarget xxx gui=bold guifg=#ff6c6b guibg=#1c1f24
    BufferInactiveSign                     { fg="#3f444a", bg="#1c1f24", }, -- BufferInactiveSign xxx guifg=#3f444a guibg=#1c1f24
    BufferInactiveMod                      { fg="#ecbe7b", bg="#1c1f24", }, -- BufferInactiveMod xxx guifg=#ECBE7B guibg=#1c1f24
    BufferInactiveIndex                    { fg="#73797e", bg="#1c1f24", }, -- BufferInactiveIndex xxx guifg=#73797e guibg=#1c1f24
    BufferInactive                         { fg="#73797e", bg="#1c1f24", }, -- BufferInactive xxx guifg=#73797e guibg=#1c1f24
    BufferVisibleTarget                    { gui="bold", fg="#ff6c6b", bg="#282c34", }, -- BufferVisibleTarget xxx gui=bold guifg=#ff6c6b guibg=#282c34
    BufferVisibleSign                      { fg="#3f444a", bg="#282c34", }, -- BufferVisibleSign xxx guifg=#3f444a guibg=#282c34
    BufferVisibleMod                       { fg="#ecbe7b", bg="#282c34", }, -- BufferVisibleMod xxx guifg=#ECBE7B guibg=#282c34
    BufferVisibleIndex                     { fg="#e6e6e6", bg="#282c34", }, -- BufferVisibleIndex xxx guifg=#E6E6E6 guibg=#282c34
    BufferVisible                          { fg="#9ca0a4", bg="#282c34", }, -- BufferVisible  xxx guifg=#9ca0a4 guibg=#282c34
    BufferCurrentTarget                    { gui="bold", fg="#ff6c6b", bg="#282c34", }, -- BufferCurrentTarget xxx gui=bold guifg=#ff6c6b guibg=#282c34
    BufferCurrentSign                      { fg="#51afef", bg="#282c34", }, -- BufferCurrentSign xxx guifg=#51afef guibg=#282c34
    BufferCurrentMod                       { fg="#ecbe7b", bg="#282c34", }, -- BufferCurrentMod xxx guifg=#ECBE7B guibg=#282c34
    BufferCurrentIndex                     { fg="#73797e", bg="#282c34", }, -- BufferCurrentIndex xxx guifg=#73797e guibg=#282c34
    BufferCurrent                          { fg="#e6e6e6", bg="#282c34", }, -- BufferCurrent  xxx guifg=#E6E6E6 guibg=#282c34
    BufferPart                             { gui="bold", fg="#da8548", bg="#6e7984", }, -- BufferPart     xxx gui=bold guifg=#da8548 guibg=#6E7984
    BufferTabpageFill                      { gui="bold", fg="#3f444a", bg="#1c1f24", }, -- BufferTabpageFill xxx gui=bold guifg=#3f444a guibg=#1c1f24
    BufferTabpages                         { gui="bold", fg="#51afef", bg="#3e4556", }, -- BufferTabpages xxx gui=bold guifg=#51afef guibg=#3E4556
    NeogitUntrackedfiles                   { gui="bold", fg="#51afef", }, -- NeogitUntrackedfiles xxx gui=bold guifg=#51afef
    NeogitUnstagedChanges                  { gui="bold", fg="#51afef", }, -- NeogitUnstagedChanges xxx gui=bold guifg=#51afef
    NeogitStashes                          { gui="bold", fg="#51afef", }, -- NeogitStashes  xxx gui=bold guifg=#51afef
    NeogitStagedChangesRegion              { bg="#21252a", }, -- NeogitStagedChangesRegion xxx guibg=#21252a
    NeogitStagedChanges                    { gui="bold", fg="#51afef", }, -- NeogitStagedChanges xxx gui=bold guifg=#51afef
    NeogitHunkHeaderHighlight              { gui="bold", fg="#21242b", bg="#a9a1e1", }, -- NeogitHunkHeaderHighlight xxx gui=bold guifg=#21242b guibg=#a9a1e1
    NeogitHunkHeader                       { fg="#282c34", bg="#4e4f67", }, -- NeogitHunkHeader xxx guifg=#282c34 guibg=#4e4f67
    NeogitDiffContextHighlight             { fg="#bbc2cf", bg="#21242b", }, -- NeogitDiffContextHighlight xxx guifg=#bbc2cf guibg=#21242b
    NeogitDiffContext                      { fg="#5b6268", bg="#282c34", }, -- NeogitDiffContext xxx guifg=#5B6268 guibg=#282c34
    NeogitDiffDeleteHighlight              { gui="bold", fg="#ff6c6b", bg="#3f343a", }, -- NeogitDiffDeleteHighlight xxx gui=bold guifg=#ff6c6b guibg=#3f343a
    NeogitDiffDelete                       { fg="#cc5655", bg="#392d34", }, -- NeogitDiffDelete xxx guifg=#cc5655 guibg=#392d34
    NeogitDiffAddHighlight                 { gui="bold", fg="#98be65", bg="#3e493d", }, -- NeogitDiffAddHighlight xxx gui=bold guifg=#98be65 guibg=#3e493d
    NeogitDiffAdd                          { fg="#799850", bg="#333a38", }, -- NeogitDiffAdd  xxx guifg=#799850 guibg=#333a38
    NvimTreeEmptyFolderName                { gui="bold", fg="#5b6268", }, -- NvimTreeEmptyFolderName xxx gui=bold guifg=#5B6268
    NvimTreeRootFolder                     { fg="#98be65", }, -- NvimTreeRootFolder xxx guifg=#98be65
    NvimTreeFolderName                     { gui="bold", fg="#51afef", }, -- NvimTreeFolderName xxx gui=bold guifg=#51afef
    NvimTreeOpenedFolderName               { NvimTreeFolderName }, -- NvimTreeOpenedFolderName xxx links to NvimTreeFolderName
    NvimTreeMarkdownFile                   { gui="underline", fg="#bbc2cf", }, -- NvimTreeMarkdownFile xxx gui=underline guifg=#bbc2cf
    NvimTreeSpecialFile                    { gui="underline", fg="#bbc2cf", }, -- NvimTreeSpecialFile xxx gui=underline guifg=#bbc2cf
    NvimTreeOpenedFile                     { fg="#5b6268", }, -- NvimTreeOpenedFile xxx guifg=#5B6268
    NvimTreeImageFile                      { fg="#51afef", }, -- NvimTreeImageFile xxx guifg=#51afef
    NvimTreeExecFile                       { gui="bold", fg="#98be65", }, -- NvimTreeExecFile xxx gui=bold guifg=#98be65
    NvimTreeSymlink                        { gui="underline", fg="#bbc2cf", }, -- NvimTreeSymlink xxx gui=underline guifg=#bbc2cf
    dashboardHeader                        { fg="#586268", }, -- dashboardHeader xxx guifg=#586268
    dashboardFooter                        { dashboardHeader }, -- dashboardFooter xxx links to dashboardHeader
    dashboardShortcut                      { fg="#9788b9", }, -- dashboardShortcut xxx guifg=#9788b9
    dashboardCenter                        { fg="#51afef", }, -- dashboardCenter xxx guifg=#51afef
    StartifyPath                           { fg="#a9a1e1", }, -- StartifyPath   xxx guifg=#a9a1e1
    StartifyNumber                         { fg="#51afef", }, -- StartifyNumber xxx guifg=#51afef
    StartifyBracket                        { fg="#3e4556", }, -- StartifyBracket xxx guifg=#3E4556
    StartifyHeader                         { fg="#3e4556", }, -- StartifyHeader xxx guifg=#3E4556
    StartifyFile                           { fg="#98be65", }, -- StartifyFile   xxx guifg=#98be65
    StartifySlash                          { fg="#a9a1e1", }, -- StartifySlash  xxx guifg=#a9a1e1
    IndentBlanklineChar                    { gui="nocombine", fg="#3f444a", }, -- IndentBlanklineChar xxx gui=nocombine guifg=#3f444a
    IndentBlanklineSpaceCharBlankline      { gui="nocombine", fg="#3f444a", }, -- IndentBlanklineSpaceCharBlankline xxx gui=nocombine guifg=#3f444a
    IndentBlanklineSpaceChar               { gui="nocombine", fg="#3f444a", }, -- IndentBlanklineSpaceChar xxx gui=nocombine guifg=#3f444a
    IndentBlanklineContextChar             { gui="nocombine", fg="#51afef", }, -- IndentBlanklineContextChar xxx gui=nocombine guifg=#51afef
    illuminatedWord                        { gui="underline", }, -- illuminatedWord xxx gui=underline
    Brown                                  { fg="#da8548", }, -- Brown          xxx guifg=#da8548
    Green                                  { fg="#98be65", }, -- Green          xxx guifg=#98be65
    Red                                    { fg="#ff6c6b", }, -- Red            xxx guifg=#ff6c6b
    Yellow                                 { fg="#ecbe7b", }, -- Yellow         xxx guifg=#ECBE7B
    Blue                                   { fg="#46d9ff", }, -- Blue           xxx guifg=#46D9FF
    ErrorMsgUnderline                      { gui="underline", fg="#ff6c6b", }, -- ErrorMsgUnderline xxx gui=underline guifg=#ff6c6b
    LspDiagnosticsUnderlineError           { ErrorMsgUnderline }, -- LspDiagnosticsUnderlineError xxx links to ErrorMsgUnderline
    MsgUnderline                           { gui="underline", fg="#98be65", }, -- MsgUnderline   xxx gui=underline guifg=#98be65
    LspDiagnosticsUnderlineHint            { MsgUnderline }, -- LspDiagnosticsUnderlineHint xxx links to MsgUnderline
    MoreMsgUnderline                       { gui="underline", fg="#51afef", }, -- MoreMsgUnderline xxx gui=underline guifg=#51afef
    LspDiagnosticsUnderlineInformation     { MoreMsgUnderline }, -- LspDiagnosticsUnderlineInformation xxx links to MoreMsgUnderline
    WarningMsgUnderline                    { gui="underline", fg="#ecbe7b", }, -- WarningMsgUnderline xxx gui=underline guifg=#ECBE7B
    LspDiagnosticsUnderlineWarning         { WarningMsgUnderline }, -- LspDiagnosticsUnderlineWarning xxx links to WarningMsgUnderline
    TSStrike                               { gui="strikethrough", fg="#8780b4", }, -- TSStrike       xxx gui=strikethrough guifg=#8780B4
    HopNextKey                             { gui="bold", fg="#ff007c", }, -- HopNextKey     xxx cterm=bold ctermfg=198 gui=bold guifg=#ff007c
    HopNextKey1                            { gui="bold", fg="#00dfff", }, -- HopNextKey1    xxx cterm=bold ctermfg=45 gui=bold guifg=#00dfff
    HopNextKey2                            { fg="#2b8db3", }, -- HopNextKey2    xxx ctermfg=33 guifg=#2b8db3
    HopUnmatched                           { sp="#666666", fg="#666666", bg="bg", }, -- HopUnmatched   xxx ctermfg=242 guifg=#666666 guibg=bg guisp=#666666
    TSNone                                 { fg="foreground", }, -- TSNone         xxx guifg=foreground
    TSText                                 { TSNone }, -- TSText         xxx links to TSNone
    TSEmphasis                             { gui="italic", }, -- TSEmphasis     xxx cterm=italic gui=italic
    TSUnderline                            { gui="underline", }, -- TSUnderline    xxx cterm=underline gui=underline
    DevIconLhs                             { fg="#a074c4", }, -- DevIconLhs     xxx ctermfg=140 guifg=#a074c4
    DevIconHrl                             { fg="#b83998", }, -- DevIconHrl     xxx ctermfg=132 guifg=#B83998
    DevIconClojure                         { fg="#8dc149", }, -- DevIconClojure xxx ctermfg=107 guifg=#8dc149
    DevIconKotlin                          { fg="#f88a02", }, -- DevIconKotlin  xxx ctermfg=208 guifg=#F88A02
    DevIconBinaryGLTF                      { fg="#ffb13b", }, -- DevIconBinaryGLTF xxx ctermfg=215 guifg=#FFB13B
    DevIconTextScene                       { fg="#a074c4", }, -- DevIconTextScene xxx ctermfg=140 guifg=#a074c4
    DevIconTxt                             { fg="#89e051", }, -- DevIconTxt     xxx ctermfg=113 guifg=#89e051
    DevIconMustache                        { fg="#e37933", }, -- DevIconMustache xxx ctermfg=173 guifg=#e37933
    DevIconRproj                           { fg="#358a5b", }, -- DevIconRproj   xxx ctermfg=65 guifg=#358a5b
    DevIconRlib                            { fg="#dea584", }, -- DevIconRlib    xxx ctermfg=180 guifg=#dea584
    DevIconProcfile                        { fg="#a074c4", }, -- DevIconProcfile xxx ctermfg=140 guifg=#a074c4
    DevIconPpt                             { fg="#cb4a32", }, -- DevIconPpt     xxx ctermfg=167 guifg=#cb4a32
    DevIconCsv                             { fg="#89e051", }, -- DevIconCsv     xxx ctermfg=113 guifg=#89e051
    DevIconConfigRu                        { fg="#701516", }, -- DevIconConfigRu xxx ctermfg=52 guifg=#701516
    DevIconCson                            { fg="#cbcb41", }, -- DevIconCson    xxx ctermfg=185 guifg=#cbcb41
    DevIconCrystal                         { fg="#000000", }, -- DevIconCrystal xxx ctermfg=16 guifg=#000000
    DevIconHeex                            { fg="#a074c4", }, -- DevIconHeex    xxx ctermfg=140 guifg=#a074c4
    DevIconCobol                           { fg="#005ca5", }, -- DevIconCobol   xxx ctermfg=25 guifg=#005ca5
    DevIconGemspec                         { fg="#701516", }, -- DevIconGemspec xxx ctermfg=52 guifg=#701516
    DevIconClojureJS                       { fg="#519aba", }, -- DevIconClojureJS xxx ctermfg=67 guifg=#519aba
    DevIconHaml                            { fg="#eaeae1", }, -- DevIconHaml    xxx ctermfg=188 guifg=#eaeae1
    DevIconClojureC                        { fg="#8dc149", }, -- DevIconClojureC xxx ctermfg=107 guifg=#8dc149
    DevIconProlog                          { fg="#e4b854", }, -- DevIconProlog  xxx ctermfg=179 guifg=#e4b854
    DevIconHs                              { fg="#a074c4", }, -- DevIconHs      xxx ctermfg=140 guifg=#a074c4
    DevIconEex                             { fg="#a074c4", }, -- DevIconEex     xxx ctermfg=140 guifg=#a074c4
    DevIconEpp                             { fg="#ffa61a", }, -- DevIconEpp     xxx guifg=#FFA61A
    DevIconFavicon                         { fg="#cbcb41", }, -- DevIconFavicon xxx ctermfg=185 guifg=#cbcb41
    DevIconErb                             { fg="#701516", }, -- DevIconErb     xxx ctermfg=52 guifg=#701516
    DevIconExs                             { fg="#a074c4", }, -- DevIconExs     xxx ctermfg=140 guifg=#a074c4
    DevIconGitCommit                       { fg="#41535b", }, -- DevIconGitCommit xxx ctermfg=59 guifg=#41535b
    DevIconCMake                           { fg="#6d8086", }, -- DevIconCMake   xxx ctermfg=66 guifg=#6d8086
    DevIconLeex                            { fg="#a074c4", }, -- DevIconLeex    xxx ctermfg=140 guifg=#a074c4
    DevIconVagrantfile                     { fg="#1563ff", }, -- DevIconVagrantfile xxx ctermfg=27 guifg=#1563FF
    DevIconXls                             { fg="#207245", }, -- DevIconXls     xxx ctermfg=23 guifg=#207245
    DevIconXcPlayground                    { fg="#e37933", }, -- DevIconXcPlayground xxx ctermfg=173 guifg=#e37933
    DevIconZshenv                          { fg="#89e051", }, -- DevIconZshenv  xxx ctermfg=113 guifg=#89e051
    DevIconZshprofile                      { fg="#89e051", }, -- DevIconZshprofile xxx ctermfg=113 guifg=#89e051
    DevIconSettingsJson                    { fg="#854cc7", }, -- DevIconSettingsJson xxx ctermfg=98 guifg=#854CC7
    DevIconAwk                             { fg="#4d5a5e", }, -- DevIconAwk     xxx ctermfg=59 guifg=#4d5a5e
    DevIconGitlabCI                        { fg="#e24329", }, -- DevIconGitlabCI xxx ctermfg=166 guifg=#e24329
    DevIconPp                              { fg="#ffa61a", }, -- DevIconPp      xxx guifg=#FFA61A
    DevIconBashrc                          { fg="#89e051", }, -- DevIconBashrc  xxx ctermfg=113 guifg=#89e051
    DevIconBashProfile                     { fg="#89e051", }, -- DevIconBashProfile xxx ctermfg=113 guifg=#89e051
    DevIconBabelrc                         { fg="#cbcb41", }, -- DevIconBabelrc xxx ctermfg=185 guifg=#cbcb41
    DevIconCxx                             { fg="#519aba", }, -- DevIconCxx     xxx ctermfg=67 guifg=#519aba
    DevIconPm                              { fg="#519aba", }, -- DevIconPm      xxx ctermfg=67 guifg=#519aba
    DevIconTex                             { fg="#3d6117", }, -- DevIconTex     xxx ctermfg=58 guifg=#3D6117
    DevIconDiff                            { fg="#41535b", }, -- DevIconDiff    xxx ctermfg=59 guifg=#41535b
    DevIconSlim                            { fg="#e34c26", }, -- DevIconSlim    xxx ctermfg=166 guifg=#e34c26
    DevIconSass                            { fg="#f55385", }, -- DevIconSass    xxx ctermfg=204 guifg=#f55385
    DevIconGDScript                        { fg="#6d8086", }, -- DevIconGDScript xxx ctermfg=66 guifg=#6d8086
    DevIconRmd                             { fg="#519aba", }, -- DevIconRmd     xxx ctermfg=67 guifg=#519aba
    DevIconWebmanifest                     { fg="#f1e05a", }, -- DevIconWebmanifest xxx ctermfg=221 guifg=#f1e05a
    DevIconPromptPs1                       { fg="#4d5a5e", }, -- DevIconPromptPs1 xxx ctermfg=59 guifg=#4d5a5e
    DevIconTor                             { fg="#519aba", }, -- DevIconTor     xxx ctermfg=67 guifg=#519aba
    DevIconZig                             { fg="#f69a1b", }, -- DevIconZig     xxx ctermfg=208 guifg=#f69a1b
    DevIconHh                              { fg="#a074c4", }, -- DevIconHh      xxx ctermfg=140 guifg=#a074c4
    DevIconNix                             { fg="#7ebae4", }, -- DevIconNix     xxx ctermfg=110 guifg=#7ebae4
    DevIconFsharp                          { fg="#519aba", }, -- DevIconFsharp  xxx ctermfg=67 guifg=#519aba
    DevIconCs                              { fg="#596706", }, -- DevIconCs      xxx ctermfg=58 guifg=#596706
    DevIconHbs                             { fg="#f0772b", }, -- DevIconHbs     xxx ctermfg=208 guifg=#f0772b
    DevIconFs                              { fg="#519aba", }, -- DevIconFs      xxx ctermfg=67 guifg=#519aba
    DevIconElm                             { fg="#519aba", }, -- DevIconElm     xxx ctermfg=67 guifg=#519aba
    DevIconDsStore                         { fg="#41535b", }, -- DevIconDsStore xxx ctermfg=59 guifg=#41535b
    DevIconDoc                             { fg="#185abd", }, -- DevIconDoc     xxx ctermfg=25 guifg=#185abd
    DevIconSml                             { fg="#e37933", }, -- DevIconSml     xxx ctermfg=173 guifg=#e37933
    DevIconNim                             { fg="#f3d400", }, -- DevIconNim     xxx ctermfg=220 guifg=#f3d400
    DevIconImportConfiguration             { fg="#ececec", }, -- DevIconImportConfiguration xxx ctermfg=231 guifg=#ECECEC
    DevIconEjs                             { fg="#cbcb41", }, -- DevIconEjs     xxx ctermfg=185 guifg=#cbcb41
    DevIconErl                             { fg="#b83998", }, -- DevIconErl     xxx ctermfg=132 guifg=#B83998
    DevIconEx                              { fg="#a074c4", }, -- DevIconEx      xxx ctermfg=140 guifg=#a074c4
    DevIconTextResource                    { fg="#cbcb41", }, -- DevIconTextResource xxx ctermfg=185 guifg=#cbcb41
    DevIconIni                             { fg="#6d8086", }, -- DevIconIni     xxx ctermfg=66 guifg=#6d8086
    DevIconConfiguration                   { fg="#ececec", }, -- DevIconConfiguration xxx ctermfg=231 guifg=#ECECEC
    DevIconDump                            { fg="#dad8d8", }, -- DevIconDump    xxx ctermfg=188 guifg=#dad8d8
    DevIconPackageLockJson                 { fg="#7a0d21", }, -- DevIconPackageLockJson xxx guifg=#7a0d21
    DevIconTwig                            { fg="#8dc149", }, -- DevIconTwig    xxx ctermfg=107 guifg=#8dc149
    DevIconLess                            { fg="#563d7c", }, -- DevIconLess    xxx ctermfg=60 guifg=#563d7c
    DevIconXul                             { fg="#e37933", }, -- DevIconXul     xxx ctermfg=173 guifg=#e37933
    DevIconCMakeLists                      { fg="#6d8086", }, -- DevIconCMakeLists xxx ctermfg=66 guifg=#6d8086
    DevIconH                               { fg="#a074c4", }, -- DevIconH       xxx ctermfg=140 guifg=#a074c4
    DevIconGodotProject                    { fg="#6d8086", }, -- DevIconGodotProject xxx ctermfg=66 guifg=#6d8086
    DevIconDropbox                         { fg="#0061fe", }, -- DevIconDropbox xxx ctermfg=27 guifg=#0061FE
    DevIconBrewfile                        { fg="#701516", }, -- DevIconBrewfile xxx ctermfg=52 guifg=#701516
    DevIconWebpack                         { fg="#519aba", }, -- DevIconWebpack xxx ctermfg=67 guifg=#519aba
    DevIconPsd                             { fg="#519aba", }, -- DevIconPsd     xxx ctermfg=67 guifg=#519aba
    DevIconPackageJson                     { fg="#e8274b", }, -- DevIconPackageJson xxx guifg=#e8274b
    DevIconD                               { fg="#427819", }, -- DevIconD       xxx ctermfg=64 guifg=#427819
    DevIconBmp                             { fg="#a074c4", }, -- DevIconBmp     xxx ctermfg=140 guifg=#a074c4
    DevIconFsx                             { fg="#519aba", }, -- DevIconFsx     xxx ctermfg=67 guifg=#519aba
    DevIconNPMrc                           { fg="#e8274b", }, -- DevIconNPMrc   xxx ctermfg=161 guifg=#E8274B
    DevIconStyl                            { fg="#8dc149", }, -- DevIconStyl    xxx ctermfg=107 guifg=#8dc149
    DevIconGif                             { fg="#a074c4", }, -- DevIconGif     xxx ctermfg=140 guifg=#a074c4
    DevIconPsb                             { fg="#519aba", }, -- DevIconPsb     xxx ctermfg=67 guifg=#519aba
    DevIconPdf                             { fg="#b30b00", }, -- DevIconPdf     xxx ctermfg=124 guifg=#b30b00
    DevIconSolidity                        { fg="#519aba", }, -- DevIconSolidity xxx ctermfg=67 guifg=#519aba
    DevIconFsscript                        { fg="#519aba", }, -- DevIconFsscript xxx ctermfg=67 guifg=#519aba
    DevIconFsi                             { fg="#519aba", }, -- DevIconFsi     xxx ctermfg=67 guifg=#519aba
    DevIconMint                            { fg="#87c095", }, -- DevIconMint    xxx ctermfg=108 guifg=#87c095
    DevIconOpenTypeFont                    { fg="#ececec", }, -- DevIconOpenTypeFont xxx ctermfg=231 guifg=#ECECEC
    DevIconMaterial                        { fg="#b83998", }, -- DevIconMaterial xxx ctermfg=132 guifg=#B83998
    DevIconCsh                             { fg="#4d5a5e", }, -- DevIconCsh     xxx ctermfg=59 guifg=#4d5a5e
    DevIconPackedResource                  { fg="#6d8086", }, -- DevIconPackedResource xxx ctermfg=66 guifg=#6d8086
    DevIconOPUS                            { fg="#f88a02", }, -- DevIconOPUS    xxx ctermfg=208 guifg=#F88A02
    DevIconSvelte                          { fg="#ff3e00", }, -- DevIconSvelte  xxx ctermfg=202 guifg=#ff3e00
    DevIconScss                            { fg="#f55385", }, -- DevIconScss    xxx ctermfg=204 guifg=#f55385
    DevIconXml                             { fg="#e37933", }, -- DevIconXml     xxx ctermfg=173 guifg=#e37933
    DevIconBat                             { fg="#c1f12e", }, -- DevIconBat     xxx ctermfg=154 guifg=#C1F12E
    DevIconMli                             { fg="#e37933", }, -- DevIconMli     xxx ctermfg=173 guifg=#e37933
    DevIconSln                             { fg="#854cc7", }, -- DevIconSln     xxx ctermfg=98 guifg=#854CC7
    DevIconMjs                             { fg="#f1e05a", }, -- DevIconMjs     xxx ctermfg=221 guifg=#f1e05a
    DevIconDesktopEntry                    { fg="#563d7c", }, -- DevIconDesktopEntry xxx ctermfg=60 guifg=#563d7c
    DevIconCoffee                          { fg="#cbcb41", }, -- DevIconCoffee  xxx ctermfg=185 guifg=#cbcb41
    DevIconMixLock                         { fg="#a074c4", }, -- DevIconMixLock xxx ctermfg=140 guifg=#a074c4
    DevIconMl                              { fg="#e37933", }, -- DevIconMl      xxx ctermfg=173 guifg=#e37933
    DevIconSig                             { fg="#e37933", }, -- DevIconSig     xxx ctermfg=173 guifg=#e37933
    DevIconFennel                          { fg="#fff3d7", }, -- DevIconFennel  xxx ctermfg=230 guifg=#fff3d7
    DevIconJl                              { fg="#a270ba", }, -- DevIconJl      xxx ctermfg=133 guifg=#a270ba
    DevIconSuo                             { fg="#e37933", }, -- DevIconSuo     xxx ctermfg=98 guifg=#e37933
    DevIconHpp                             { fg="#a074c4", }, -- DevIconHpp     xxx ctermfg=140 guifg=#a074c4
    DevIconGulpfile                        { fg="#cc3e44", }, -- DevIconGulpfile xxx ctermfg=167 guifg=#cc3e44
    DevIconGruntfile                       { fg="#e37933", }, -- DevIconGruntfile xxx ctermfg=173 guifg=#e37933
    DevIconKsh                             { fg="#4d5a5e", }, -- DevIconKsh     xxx ctermfg=59 guifg=#4d5a5e
    DevIconEdn                             { fg="#519aba", }, -- DevIconEdn     xxx ctermfg=67 guifg=#519aba
    DevIconAi                              { fg="#cbcb41", }, -- DevIconAi      xxx ctermfg=185 guifg=#cbcb41
    DevIconGitModules                      { fg="#41535b", }, -- DevIconGitModules xxx ctermfg=59 guifg=#41535b
    DevIconHxx                             { fg="#a074c4", }, -- DevIconHxx     xxx ctermfg=140 guifg=#a074c4
  }
end)
