
local kind = {
  Text = "",
  -- Method = "m",
  -- Function = "",
  -- Constructor = "",
  Method = "",
  Function = "",
  Constructor = "",
  Field = "ﰠ", --"",
  Variable = "",
  -- Variable = "",
  Class = "ﴯ", --"",
  Interface = "",
  Module = "",
  -- Module = "",
  -- Property = "",
  Property = "ﰠ",
  Unit = "",
  Value = "",
  Enum = "",
  Keyword = "",
  -- Keyword = "",
  Snippet = "",
  -- Snippet = "",
  Color = "",
  File = "",
  Reference = "",
  Folder = "",
  EnumMember = "",
  -- Constant = "",
  Constant = "",
  -- Struct = "פּ",
  Struct = "",
  Event = "",
  Operator = "",
  TypeParameter = "",
}

return {
  kind = kind,
  documents = {
    arrow = {
      open = "",
      closed = "",
    },
    folder = {
      default = "",
      open = "",
      symlink = "",
      empty = "",
      empty_open = "",
    },
    file = {
      default = "",
      symlink = "",
      files = "",
    },
    git = {
      unstaged = "",
      staged = "s",
      unmerged = "",
      renamed = "➜",
      deleted = "",
      untracked = "u",
      ignored = "◌",
    },
  },
  git = {
    add = "",
    mod = "",
    remove = "",
    ignore = "",
    rename = "",
    diff = "",
    repo = "",
    branch = "",
  },
  ui = {
    lock = "",
    circle = "",
    bigcircle = "",
    bigunfilledcircle = "",
    close = "",
    newfile = "",
    search = "",
    lightbulb = "",
    project = "",
    dashboard = "",
    history = "",
    comment = "",
    bug = "",
    code = "",
    telescope = "",
    gear = "",
    package = "",
    list = "",
    signin = "",
    check = "",
    fire = "",
    tree = "",
    note = "",
    bookmark = "",
    pencil = "",
    -- chevronright = "",
    chevronright = ">",
    table = "",
    calendar = "",
    update = "",
    download = "",
    pause = "",
    cross = "",
    ok = "",
    expand = "ﬕ",
    spinnerframes = { "⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷" },
  },
  diagnostics = {
    error = "", -- "", -- ""
    warning = "", -- "", -- ""
    information = "", -- "", -- ""
    question = "", --"", -- ""
    hint = "", -- "", -- ""
  },
  misc = {
    robot = "ﮧ",
    squirrel = "",
    tag = "",
    watch = "",
    terminal = ""
  },
}
